edition = "2021"

max_width = 120

indent_style = "Block"
reorder_imports = true

imports_granularity = "Module"
group_imports = "StdExternalCrate"

format_macro_matchers = true
spaces_around_ranges = true
tab_spaces = 4
use_field_init_shorthand = true
