[package]
name = "conformance"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0.66"
byteorder = "1.4.3"
protokit = { path = "../../protokit" }




[build-dependencies]
cmake = "0.1.49"
bindgen = "0.64.0"
protokit_build = { path = "../../protokit_build" }

