fn main() {
    protokit_build::Build::new()
        .include(".")
        .include("../../vendor/protobuf/src")
        .out_dir("src/gen")
        .textformat(true)
        // .string_type("Box<str>")
        // .bytes_type("Box<[u8]>")
        // .compile("google/protobuf/struct.proto")
        // .unwrap()
        .compile("google/protobuf/descriptor.proto")
        .unwrap()
        .compile("google/protobuf/api.proto")
        .unwrap()
        .compile("google/protobuf/compiler/plugin.proto")
        .unwrap()
        .compile("google/protobuf/struct.proto")
        .unwrap()
        .compile("google/protobuf/timestamp.proto")
        .unwrap()
        .compile("fuzz.proto")
        .unwrap()
        .generate()
        .unwrap()
}
