fn main() {
    protokit_codegen::Codegen::new()
        .include("../proto")
        // .include("../vendor/protobuf/src")
        .out_dir("src/gen")
        .textformat(true)
        // .string_type("Box<str>")
        // .bytes_type("Box<[u8]>")
        // .compile("google/protobuf/struct.proto")
        // .unwrap()
        .compile("google/protobuf/descriptor.proto")
        .unwrap()
        .compile("google/protobuf/api.proto")
        .unwrap()
        .compile("google/protobuf/compiler/plugin.proto")
        .unwrap()
        .compile("google/protobuf/struct.proto")
        .unwrap()
        .compile("com/book/book.proto")
        .unwrap()
        .compile("google/protobuf/timestamp.proto")
        .unwrap()
        .generate()
        .unwrap()
}
