[package]
name = "protokit_examples"
version = "0.1.0"
edition = "2021"
build = "build.rs"
publish = false

[dependencies]
protokit = { path = "../protokit", features = [] }

[build-dependencies]
protokit_build = { path = "../protokit_build" }

[dev-dependencies]
include_dir = "0.7.2"