name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Vendor
      run: ./scripts/vendor.sh

    - name: Prepare
      run: apt-get update && apt-get install protobuf-compiler

    - name: Build
      run: RUST_BACKTRACE=full cargo build

    - name: Run tests
      run: RUST_BACKTRACE=full cargo test

    - name: Verify conformance
      run: ./scripts/conformance.sh
